Repository gii-is-psg2/PSG2-2021-G2-22, pull requests merged in 2021-05, with the labels that each got.

#101 Feature/55 extra2
  src/main/java/org/springframework/samples/petclinic/PetclinicApplication.java
  src/main/java/org/springframework/samples/petclinic/configuration/ExceptionHandlerConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/WebConfig.java
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Person.java
  src/main/java/org/springframework/samples/petclinic/model/Pet.java
  src/main/java/org/springframework/samples/petclinic/model/Vet.java
  src/main/java/org/springframework/samples/petclinic/model/Vets.java
  src/main/java/org/springframework/samples/petclinic/model/Visit.java
  src/main/java/org/springframework/samples/petclinic/repository/OwnerRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/PetRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/VetRepository.java
  src/main/java/org/springframework/samples/petclinic/service/AdoptionService.java
  src/main/java/org/springframework/samples/petclinic/service/AuthoritiesService.java
  src/main/java/org/springframework/samples/petclinic/service/CauseService.java
  src/main/java/org/springframework/samples/petclinic/service/VetService.java
  src/main/java/org/springframework/samples/petclinic/util/CauseValidator.java
  src/main/java/org/springframework/samples/petclinic/util/EntityUtils.java
  src/main/java/org/springframework/samples/petclinic/util/ReservationValidator.java
  src/main/java/org/springframework/samples/petclinic/web/AdoptionController.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
  src/main/java/org/springframework/samples/petclinic/web/HotelController.java
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/java/org/springframework/samples/petclinic/web/PetFormatter.java
  src/main/java/org/springframework/samples/petclinic/web/PetTypeFormatter.java
  src/main/java/org/springframework/samples/petclinic/web/SpecialtyFormatter.java
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/java/org/springframework/samples/petclinic/web/VetController.java
  src/main/java/org/springframework/samples/petclinic/web/VisitController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
  src/test/java/org/springframework/samples/petclinic/service/OwnerServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/PetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/VetServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AdoptionControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/CrashControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/OwnerControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/PetTypeFormatterTests.java
  src/test/java/org/springframework/samples/petclinic/web/VetControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/VisitControllerTests.java
Labels: review

#108 Feature/52 informe metricas y recursos
  src/main/resources/doc/Informes técnicos/S3/1. Informe técnico “Métricas de Proceso Ágil y Recursos”.docx
Labels: review

#144 Completado health check
  pom.xml
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/web/HealthController.java
  src/main/less/header.less
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/jsp/health/info.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: review

#153 Documento de la tarea 124
  src/main/resources/doc/Informes técnicos/S4/1. Informe técnico Bases de Datos de Gestión de la Configuración de la Organización PSG2-2021-G2-22.docx
Labels: review

#158 Terminado apartado de estructura de la CMDB
  src/main/resources/doc/Informes técnicos/S4/1. Informe técnico Bases de Datos de Gestión de la Configuración de la Organización PSG2-2021-G2-22.docx
Labels: review

#152 Actualización Informe Técnico CMDB
  src/main/resources/doc/Informes técnicos/S4/1. Informe técnico Bases de Datos de Gestión de la Configuración de la Organización PSG2-2021-G2-22.docx
Labels: documentation, review

#160 #123 Actualización sección DSL de apartado estructura de la CMDB
  src/main/resources/doc/Informes técnicos/S4/1. Informe técnico Bases de Datos de Gestión de la Configuración de la Organización PSG2-2021-G2-22.docx
Labels: review

#161 Añadido apartado de Objetivo de nivel de servicio mediante métricas TTO y TTR
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
Labels: review

#159 Feature/128 mantenimiento
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
Labels: review

#167 Feature/130 proporcion de garantia
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22 (1).docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
Labels: review

#169 Tarea 127
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22 (1).docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
Labels: review

#172 Incidencia I-000650 resuelta.
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
Labels: review

#178 Cambio fuente del servicio y su tamaño
  src/main/less/header.less
  src/main/less/typography.less
Labels: review

#181 Hotfix/3.0.1 179 i 000885
  src/main/webapp/WEB-INF/jsp/causes/listCauseDetails.jsp
Labels: review

#180 Indicente arreglado correctamente
  src/main/webapp/WEB-INF/jsp/causes/listCauseDetails.jsp
Labels: review

#183 Epic/126 sla mantenimiento
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
Labels: review

#193 Resuelta la incidencia
  src/main/resources/static/resources/images/mascotas.jpeg
Labels: review

#191 Añade informe extra 2
  src/main/resources/doc/Informe extra task 2 PSG2-2021-G2-22.docx
Labels: review

#200 Feature/188 r 000960
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/less/petclinic.less
  src/main/resources/doc/Actas Daily Scrum/S4/Daily Scrum 14 mayo.docx
  src/main/resources/doc/Actas Daily Scrum/S4/Daily Scrum 21 mayo - copia.docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
  src/main/webapp/WEB-INF/jsp/causes/listCauseDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
Labels: review

#195 Botón de idiomas
  src/main/java/org/springframework/samples/petclinic/configuration/LocaleConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/WebConfig.java
  src/main/less/petclinic.less
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_en.properties
  src/main/resources/messages/messages_es.properties
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: review

#201 Hotfix/3.0.3 197 i 000978
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/less/header.less
  src/main/less/typography.less
  src/main/resources/static/resources/images/mascotas.jpeg
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
Labels: review

#202 Hotfix/3.0.3 197 i 000978
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/java/org/springframework/samples/petclinic/web/PetController.java
  src/main/less/header.less
  src/main/less/typography.less
  src/main/resources/static/resources/images/mascotas.jpeg
  src/main/webapp/WEB-INF/jsp/owners/ownerDetails.jsp
  src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
Labels: review

#194 Solicitud de cambio menú usuario realizada
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: review

#207 Hotfix/3.1.1 206 i 001040
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Donation.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
Labels: review

#208 Incidencia I-001040 resuelta
  src/main/java/org/springframework/samples/petclinic/model/Cause.java
  src/main/java/org/springframework/samples/petclinic/model/Donation.java
  src/main/java/org/springframework/samples/petclinic/web/CauseController.java
Labels: review

#210 Tarea 136
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22 .docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
  src/main/resources/doc/Informes técnicos/S4/Diseño extensión para Petclinic y TCO.docx
Labels: review

#209 Feature/135 descripcion y tco
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
  src/main/resources/doc/Informes técnicos/S4/Diseño extensión para Petclinic y TCO.docx
Labels: review

#213 Mejora del documento
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
Labels: review

#216 Feature/139 extra1
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/resources/doc/Actas Daily Scrum/S4/Daily Scrum 14 mayo.docx
  src/main/resources/doc/Actas Daily Scrum/S4/Daily Scrum 21 mayo - copia.docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22 (2).docx
  src/main/resources/doc/Informes técnicos/S4/Diseño extensión para Petclinic y TCO.docx
  src/main/webapp/WEB-INF/jsp/causes/listCauseDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
Labels: Epic, documentation

#214 Feature/137 analisis servicio ampliado
  src/main/java/org/springframework/samples/petclinic/web/OwnerController.java
  src/main/resources/doc/Actas Daily Scrum/S4/Daily Scrum 14 mayo.docx
  src/main/resources/doc/Actas Daily Scrum/S4/Daily Scrum 21 mayo - copia.docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22 (2) (2).docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
  src/main/webapp/WEB-INF/jsp/causes/listCauseDetails.jsp
  src/main/webapp/WEB-INF/jsp/owners/ownersList.jsp
Labels: review

#218 Epic/134 extension
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22 (2).docx
  src/main/resources/doc/Informes técnicos/S4/2. Informe técnico SLA del servicio de mantenimiento para la clínica de mascotas PSG2-2021-G2-22.docx
  src/main/resources/doc/Informes técnicos/S4/Diseño extensión para Petclinic y TCO.docx
Labels: review

#220 Niko niko
  nikoniko.md
Labels: review

#223 Elimina documento innecesario Daily S4
  src/main/resources/doc/Actas Daily Scrum/S4/~$ Daily Scrum 21 mayo.docx
Labels: review
